### PR TITLE
Add contribute section to menu and update contribution Documentation

### LINKED ISSUE #83: ts/react/free2z: Add "Contribute" to the AvatarMenu
## What

Link to Github from avatar menu

## Why

People can contribute now

## Acceptance Criteria

- [ ] Link to ts/react/free2z/README.md
- [ ] Have nice contributor section in README, describe program, link to issues

### PR DESCRIPTION
**Pull request by 0bkevin**
### Description
This pull request includes the following changes:

1. [x]  Add Contribute Section to Menu:
    - Details: Added a "Contribute" section to the main menu to encourage community contributions and make it easier for users to find contribution guidelines.

2. [x] Update README and add Contribution Guidelines (CONTRIBUTING.md):
    - Details: Updated the README file to include, and create a detailed contribution guidelines, providing clear instructions for new contributors on how to get started.

### Types of Changes

-  Update existing feature (non-breaking change which adds functionality)
-  Documentation update

### Checklist
- The code follows the code style of this project.
-  My change requires a change to the documentation.
-  I have updated the documentation accordingly.

### Linked Issues
Closes #83

### CODE REVIEW

**Comment by skyl** [comment]
Awesome! Let me build and try these and see about deploying to prod and getting you paid!

**Comment by skyl** [comment]
going to test.free2z.com now 🚀

**Comment by skyl** [comment]
Thanks @0bkevin - looks good - let me know if you have a page on free2z or an address I can send you some ZEC. I was thinking about starting a little process where someone makes a well specified issue, we label it with a ZEC price and pay the developer when it goes to production. I was thinking maybe the one who specified the issue gets 10% on top of the price. So, like a 2 ZEC issue would pay 2 ZEC to the developer + 0.2 ZEC to the one who made the actionable description / acceptance criteria.

- make issue
- agree to bounty
- send to production & pay bounty

**Review by skyl — APPROVED** [review]

**Comment by skyl** [comment]
A nice little extra I'll probably add in a second is a link to the github in the footer (for people who aren't logged in).

**Comment by 0bkevin** [comment]
> Thanks @0bkevin - looks good - let me know if you have a page on free2z or an address I can send you some ZEC.

@skyl I'm happy to help. I really love the project, hope to be able to continue contributing 💚

Yes, this is my user in Free2z 👉 [@0bkevin](https://free2z.com/0bkevin).  You can find my address there. 

> I was thinking about starting a little process where someone makes a well specified issue, we label it with a ZEC price and pay the developer when it goes to production. I was thinking maybe the one who specified the issue gets 10% on top of the price. So, like a 2 ZEC issue would pay 2 ZEC to the developer + 0.2 ZEC to the one who made the actionable description / acceptance criteria.

I love the idea. It could incentivize users to report bugs and ask for new functionalities. This could also get more developers on board. I could extend the contribution guidelines to include this. Additionally, I think we should specify the bounties process and minimal requirements more clearly to avoid potential problems.

**Pull request merged**
